### ISSUE TITLE
Test `scope` not working with svelte 3.35.0

### ISSUE THREAD

**Issue by mathieumure** [sveltejs/eslint-plugin-svelte3#94]
On master when running the test with svelte 3.35.0 (not happening with 3.34.0)

```
scope
assert.js:105
  throw new AssertionError(obj);
  ^

AssertionError [ERR_ASSERTION]: 5 == 6
    at Object.<anonymous> (~/eslint-plugin-svelte3/test/index.js:20:10)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47 {
  generatedMessage: true,
  code: 'ERR_ASSERTION',
  actual: 5,
  expected: 6,
  operator: '=='
}

```

**Comment by dummdidumm** [comment]
Do you mean Svelte instead of Prettier?

**Comment by mathieumure** [comment]
Ho yeah you're right 😅 I fix it

**Comment by Conduitry** [comment]
I think this is a bug in Svelte. The AST that's generated for `<Component2><div slot='foo' let:blah={blah2}>{blah1}{blah2}</div></Component2>` (the part of the test that's failing) looks like it's missing some stuff in 3.35.0. It's just

```
{
  start: 0,
  end: 78,
  type: 'Fragment',
  children: [
    {
      start: 0,
      end: 78,
      type: 'InlineComponent',
      name: 'Component2',
      attributes: [],
      children: []
    }
  ]
}
```

in 3.35.0 - none of the children of `Component2` are present.

**Comment by Conduitry** [comment]
Svelte 3.36.0 has been released, which fixes the AST bug that was causing this.
